### ISSUE TITLE
ROS 2ブリッジ使用時の車速仕様

### ISSUE THREAD

**Issue by atinfinity** [pf-robotics/kachaka-api#112]
<https://kachaka.zendesk.com/hc/ja/articles/8764251540367-カチャカの最高速度が知りたい>に

> 「動く速さ」の設定値に従って移動速度は変化します。

とあります。ROS 2ブリッジ使用時にcmd_velで走行させる場合、アプリ側の「動く速さ」の設定値は作用するのでしょうか？また、cmd_velでこの設定値を超えた速度指示を出してしまった場合の振る舞いについて教えて頂きたいです（上限値でクリップされる？無効な速度指示として無視される？）

**Comment by atinfinity** [comment]
@terakoji-pfr お手数ですがご見解頂けますでしょうか？

**Comment by terakoji-pfr** [comment]
ご質問ありがとうございます。
cmd_velで走行させる場合、アプリ側の動く速さの設定値は影響を受けません。

目的地にkachakaのnavigation経由で移動した場合は、アプリ側の動く速さで制限されます。

**Comment by atinfinity** [comment]
@terakoji-pfr ご回答ありがとうございました。
