### ISSUE TITLE
カチャカ標準のナビゲーション機能をオフにしたい

### ISSUE THREAD

**Issue by GAI-313** [pf-robotics/kachaka-api#121]
失礼します。ROS2 Navigation2 とカチャカの LiDAR センサーを使用してマッピングを実装したいのですが、カチャカ標準のナビゲーション機能により正常にマップを作成することができませんでした。<br>
　カチャカ標準のナビゲーションをオフにし、トピック `/kachaka/mapping/map` へのパブリッシュを無効化することは可能でしょうか？

**Comment by atinfinity** [comment]
<https://github.com/pf-robotics/kachaka-api/issues/105#issuecomment-2238173114>でコメントもらいました。私はマッピングはカチャカの機能を使ってlocalizationだけ別でやりたかったので<https://zenn.dev/ame_b/articles/da4636a0a8048f>を参考にしました。
